import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export interface JourneyData {
  startDate: Date;
  endDate: Date;
  topPatterns: Array<{ name: string; intensity: number; color: string }>;
  sessionCount: number;
  totalHours: number;
  breakthroughCount: number;
  insights: string[];
}

/**
 * Generates a formatted PDF report of the user's pattern recognition journey.
 * Includes mood trends charts, timeline summaries, and key insights.
 */
export async function generateJourneyPDF(
  journeyData: JourneyData,
  elementId?: string
) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;
  const contentWidth = pageWidth - 2 * margin;

  let yPosition = margin;

  // Set fonts
  const titleFont = 'serif';
  const bodyFont = 'helvetica';

  // Header with title
  doc.setFont(titleFont, 'bold');
  doc.setFontSize(24);
  doc.setTextColor(201, 169, 110); // Gold color
  doc.text('Your Pattern Recognition Journey', margin, yPosition);

  yPosition += 15;
  doc.setFont(bodyFont, 'normal');
  doc.setFontSize(10);
  doc.setTextColor(100);

  const dateRange = `${journeyData.startDate.toLocaleDateString()} — ${journeyData.endDate.toLocaleDateString()}`;
  doc.text(dateRange, margin, yPosition);

  yPosition += 15;

  // Summary Stats
  doc.setFont(titleFont, 'bold');
  doc.setFontSize(14);
  doc.setTextColor(201, 169, 110);
  doc.text('Your Journey at a Glance', margin, yPosition);

  yPosition += 10;
  doc.setFont(bodyFont, 'normal');
  doc.setFontSize(11);
  doc.setTextColor(50);

  const stats = [
    `Sessions Completed: ${journeyData.sessionCount}`,
    `Total Hours Invested: ${journeyData.totalHours.toFixed(1)}`,
    `Key Breakthroughs: ${journeyData.breakthroughCount}`,
  ];

  stats.forEach((stat) => {
    doc.text(stat, margin + 5, yPosition);
    yPosition += 7;
  });

  yPosition += 5;

  // Top Patterns
  doc.setFont(titleFont, 'bold');
  doc.setFontSize(14);
  doc.setTextColor(201, 169, 110);
  doc.text('Top Active Patterns', margin, yPosition);

  yPosition += 10;

  journeyData.topPatterns.forEach((pattern) => {
    // Pattern color box
    const rgbColor = pattern.color.match(/\d+/g) || ['201', '169', '110'];
    doc.setFillColor(
      parseInt(rgbColor[0]),
      parseInt(rgbColor[1]),
      parseInt(rgbColor[2])
    );
    doc.rect(margin + 2, yPosition - 2, 3, 3, 'F');

    // Pattern name and intensity
    doc.setFont(bodyFont, 'bold');
    doc.setFontSize(10);
    doc.setTextColor(50);
    doc.text(`${pattern.name}`, margin + 7, yPosition);

    // Intensity bar
    const barWidth = contentWidth - 40;
    const filledWidth = (pattern.intensity / 100) * barWidth;
    doc.setDrawColor(230);
    doc.rect(margin + 40, yPosition - 2.5, barWidth, 3);
    doc.setFillColor(
      parseInt(rgbColor[0]),
      parseInt(rgbColor[1]),
      parseInt(rgbColor[2])
    );
    doc.rect(margin + 40, yPosition - 2.5, filledWidth, 3, 'F');

    doc.setFont(bodyFont, 'normal');
    doc.setFontSize(9);
    doc.setTextColor(120);
    doc.text(`${pattern.intensity}%`, pageWidth - margin - 10, yPosition);

    yPosition += 8;
  });

  yPosition += 8;

  // Key Insights
  if (journeyData.insights.length > 0) {
    doc.setFont(titleFont, 'bold');
    doc.setFontSize(14);
    doc.setTextColor(201, 169, 110);
    doc.text('Key Insights', margin, yPosition);

    yPosition += 10;

    doc.setFont(bodyFont, 'normal');
    doc.setFontSize(10);
    doc.setTextColor(50);

    journeyData.insights.forEach((insight, index) => {
      const lines = doc.splitTextToSize(insight, contentWidth - 5);
      lines.forEach((line: string) => {
        if (yPosition > pageHeight - margin - 10) {
          doc.addPage();
          yPosition = margin;
        }
        doc.text(line, margin + 3, yPosition);
        yPosition += 5;
      });
      yPosition += 2;
    });
  }

  // Footer
  yPosition = pageHeight - margin - 10;
  doc.setFont(bodyFont, 'normal');
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text(
    'Generated by AstroKalki Pattern Recognition System',
    margin,
    yPosition
  );
  doc.text(`${new Date().toLocaleDateString()}`, pageWidth - margin - 30, yPosition);

  return doc;
}

/**
 * Exports a specific HTML element as a PDF (for charts, timelines, etc.)
 */
export async function exportElementAsPDF(
  elementId: string,
  filename: string,
  title?: string
) {
  const element = document.getElementById(elementId);
  if (!element) {
    console.error(`Element with ID "${elementId}" not found`);
    return;
  }

  try {
    // Capture the element as a canvas
    const canvas = await html2canvas(element, {
      backgroundColor: '#050505',
      scale: 2,
    });

    // Create PDF
    const doc = new jsPDF({
      orientation: canvas.width > canvas.height ? 'landscape' : 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 10;

    // Add title if provided
    if (title) {
      doc.setFont('serif', 'bold');
      doc.setFontSize(16);
      doc.setTextColor(201, 169, 110);
      doc.text(title, margin, margin + 5);
    }

    // Calculate image dimensions
    const imgWidth = pageWidth - 2 * margin;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    const startY = title ? margin + 15 : margin;

    // Add image to PDF
    const imgData = canvas.toDataURL('image/png');
    doc.addImage(
      imgData,
      'PNG',
      margin,
      startY,
      imgWidth,
      Math.min(imgHeight, pageHeight - startY - margin)
    );

    // Save the PDF
    doc.save(filename);
  } catch (error) {
    console.error('Error generating PDF:', error);
  }
}

/**
 * Downloads the journey data as a formatted PDF file
 */
export async function downloadJourneyPDF(
  journeyData: JourneyData,
  filename: string = 'my-pattern-journey.pdf'
) {
  try {
    const pdf = await generateJourneyPDF(journeyData);
    pdf.save(filename);
  } catch (error) {
    console.error('Error downloading journey PDF:', error);
    throw error;
  }
}
