#!/bin/bash
# ═══════════════════════════════════════════════════════════════════
# AstroKalki + Self-hosted Cal.com (cal.diy) — Setup Script
# ═══════════════════════════════════════════════════════════════════
#
# This script sets up the complete stack:
#   1. Cal.com (cal.diy) on port 3001
#   2. AstroKalki on port 3000
#   3. PostgreSQL + Redis via Docker
#
# REQUIREMENTS:
#   - Docker & Docker Compose installed
#   - 8GB+ RAM recommended
#   - Git
#
# USAGE:
#   chmod +x scripts/setup-cal.sh
#   ./scripts/setup-cal.sh
#
set -euo pipefail

# ─── Colors ──────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info()  { echo -e "${BLUE}[INFO]${NC} $*"; }
ok()    { echo -e "${GREEN}[OK]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
err()   { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

# ─── Pre-flight checks ─────────────────────────────────────────
info "Checking prerequisites..."

command -v docker >/dev/null 2>&1 || err "Docker is not installed. Install from https://docs.docker.com/get-docker/"
command -v docker compose >/dev/null 2>&1 || command -v docker-compose >/dev/null 2>&1 || err "Docker Compose is not installed."
command -v git >/dev/null 2>&1 || err "Git is not installed."

# Check memory
TOTAL_MEM_KB=$(grep MemTotal /proc/meminfo 2>/dev/null | awk '{print $2}')
TOTAL_MEM_MB=$((TOTAL_MEM_KB / 1024))
if [ "$TOTAL_MEM_MB" -lt 6000 ]; then
  warn "Only ${TOTAL_MEM_MB}MB RAM detected. 8GB+ recommended for cal.diy."
fi
ok "Prerequisites check passed (${TOTAL_MEM_MB}MB RAM available)"

# ─── Generate secrets ───────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_ROOT/.env.cal"

if [ ! -f "$ENV_FILE" ]; then
  info "Generating secrets for Cal.com..."
  CAL_NEXTAUTH_SECRET=$(openssl rand -base64 32)
  CAL_ENCRYPTION_KEY=$(openssl rand -base64 24)
  CAL_POSTGRES_PASSWORD=$(openssl rand -base64 16 | tr -d '=/+' | head -c 20)

  cat > "$ENV_FILE" << EOF
# ─── Cal.com Self-hosted Configuration ───────────────────────
# Generated by scripts/setup-cal.sh on $(date)

CAL_POSTGRES_PASSWORD=$CAL_POSTGRES_PASSWORD
CAL_NEXTAUTH_SECRET=$CAL_NEXTAUTH_SECRET
CAL_ENCRYPTION_KEY=$CAL_ENCRYPTION_KEY

# Set this to your public URL (e.g., https://cal.yourdomain.com)
CAL_PUBLIC_URL=http://localhost:3001

# Your Cal.com username (the first part of the booking link)
CAL_USERNAME=astrokalki
EOF
  ok "Secrets saved to $ENV_FILE"
else
  ok "Cal.com config already exists at $ENV_FILE"
fi

# ─── Source config ──────────────────────────────────────────────
source "$ENV_FILE"

# ─── Update AstroKalki .env ────────────────────────────────────
info "Updating AstroKalki .env to point to self-hosted Cal.com..."
ASTRO_ENV="$PROJECT_ROOT/.env"

if ! grep -q "NEXT_PUBLIC_CAL_ORIGIN" "$ASTRO_ENV" 2>/dev/null; then
  cat >> "$ASTRO_ENV" << EOF

# ─── Cal.com (Self-hosted via cal.diy) ───────────────────────
NEXT_PUBLIC_CAL_LINK="\${CAL_USERNAME:-astrokalki}/consultation"
NEXT_PUBLIC_CAL_ORIGIN="\${CAL_PUBLIC_URL:-http://localhost:3001}"
EOF
  ok "Added Cal.com config to $ASTRO_ENV"
else
  sed -i "s|^NEXT_PUBLIC_CAL_ORIGIN=.*|NEXT_PUBLIC_CAL_ORIGIN=${CAL_PUBLIC_URL:-http://localhost:3001}|" "$ASTRO_ENV"
  ok "Updated Cal.com origin in $ASTRO_ENV"
fi

# ─── Configure cal.diy .env ────────────────────────────────────
CAL_DIR="$PROJECT_ROOT/cal-diy"
CAL_ENV="$CAL_DIR/.env"

if [ ! -f "$CAL_ENV" ] && [ -f "$CAL_DIR/.env.example" ]; then
  info "Creating cal.diy .env from .env.example..."
  cp "$CAL_DIR/.env.example" "$CAL_ENV"
fi

if [ -f "$CAL_ENV" ]; then
  info "Configuring cal.diy .env..."
  # Set database URL
  sed -i "s|^DATABASE_URL=.*|DATABASE_URL=postgresql://calcom:${CAL_POSTGRES_PASSWORD}@postgres:5432/calcom|" "$CAL_ENV"
  sed -i "s|^DATABASE_DIRECT_URL=.*|DATABASE_DIRECT_URL=postgresql://calcom:${CAL_POSTGRES_PASSWORD}@postgres:5432/calcom|" "$CAL_ENV"
  # Set auth
  sed -i "s|^NEXTAUTH_URL=.*|NEXTAUTH_URL=${CAL_PUBLIC_URL:-http://localhost:3001}|" "$CAL_ENV"
  sed -i "s|^NEXTAUTH_SECRET=.*|NEXTAUTH_SECRET=${CAL_NEXTAUTH_SECRET}|" "$CAL_ENV"
  sed -i "s|^CALENDSO_ENCRYPTION_KEY=.*|CALENDSO_ENCRYPTION_KEY=${CAL_ENCRYPTION_KEY}|" "$CAL_ENV"
  # Set URLs
  sed -i "s|^NEXT_PUBLIC_WEBAPP_URL=.*|NEXT_PUBLIC_WEBAPP_URL=${CAL_PUBLIC_URL:-http://localhost:3001}|" "$CAL_ENV"
  sed -i "s|^NEXT_PUBLIC_API_URL=.*|NEXT_PUBLIC_API_URL=${CAL_PUBLIC_URL:-http://localhost:3001}/api|" "$CAL_ENV"
  sed -i "s|^NEXT_PUBLIC_EMBED_LIB_URL=.*|NEXT_PUBLIC_EMBED_LIB_URL=${CAL_PUBLIC_URL:-http://localhost:3001}/embed/embed.js|" "$CAL_ENV"
  # Disable heavy features
  grep -q "^DISABLE_VIDEOS" "$CAL_ENV" || echo "DISABLE_VIDEOS=true" >> "$CAL_ENV"
  grep -q "^NEXT_PUBLIC_LOGGER_LEVEL" "$CAL_ENV" || echo "NEXT_PUBLIC_LOGGER_LEVEL=5" >> "$CAL_ENV"
  # Redis
  grep -q "^REDIS_URL" "$CAL_ENV" || echo "REDIS_URL=redis://redis:6379" >> "$CAL_ENV"

  # Copy to prisma package
  cp "$CAL_ENV" "$CAL_DIR/packages/prisma/.env" 2>/dev/null || true

  ok "cal.diy .env configured"
fi

# ─── Start services ─────────────────────────────────────────────
info "Starting services with Docker Compose..."
cd "$PROJECT_ROOT"

docker compose up -d --build 2>&1 | tail -20

# ─── Wait for Cal.com to be healthy ─────────────────────────────
info "Waiting for Cal.com to start (this may take 2-3 minutes)..."
MAX_WAIT=180
WAITED=0
while [ $WAITED -lt $MAX_WAIT ]; do
  if curl -sf "${CAL_PUBLIC_URL:-http://localhost:3001}/api/health" >/dev/null 2>&1; then
    ok "Cal.com is running at ${CAL_PUBLIC_URL:-http://localhost:3001}"
    break
  fi
  sleep 5
  WAITED=$((WAITED + 5))
  echo -n "."
done
echo ""

if [ $WAITED -ge $MAX_WAIT ]; then
  warn "Cal.com didn't respond in time. Check: docker compose logs cal"
fi

# ─── Seed database ─────────────────────────────────────────────
info "Seeding Cal.com database with test users..."
cd "$CAL_DIR"
docker compose -f "$PROJECT_ROOT/docker-compose.yml" exec -T cal \
  yarn workspace @calcom/prisma db-seed 2>&1 | tail -5 || \
  warn "Seed failed — you can seed manually later with: cd cal-diy && yarn workspace @calcom/prisma db-seed"

# ─── Done ───────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Setup Complete!${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${BLUE}Cal.com Admin:${NC}  http://localhost:3001"
echo -e "  ${BLUE}AstroKalki:${NC}     http://localhost:3000"
echo ""
echo "  Test accounts (Cal.com):"
echo "    admin@example.com  /  ADMINadmin2022!  (Admin)"
echo "    pro@example.com     /  pro              (Pro)"
echo "    free@example.com    /  free             (Free)"
echo ""
echo "  Next steps:"
echo "    1. Login at http://localhost:3001 with admin@example.com"
echo "    2. Go to Settings → Event Types → Create a 'consultation' event"
echo "    3. Set your availability in Settings → Availability"
echo "    4. Open http://localhost:3000 and test the booking flow"
echo ""
echo "  Useful commands:"
echo "    docker compose logs -f cal    # Watch Cal.com logs"
echo "    docker compose logs -f app    # Watch AstroKalki logs"
echo "    docker compose down           # Stop everything"
echo "    docker compose up -d          # Start again"
echo ""